### ISSUE TITLE
Allow Ingress Url Path based routing

### ISSUE THREAD

**Issue by mattalberts** [cloudflare/cloudflare-ingress-controller#123]
The ingress controller does not support url based routing (the IngressPath attribute `Path`)

```
spec:
  rules:
  - host: echo.mydomain.com
    http:
      paths:
      - backend:
      - path: any_path_is_treated_as_slash
          serviceName: echo
          servicePort: http
```

**Comment by mattalberts** [comment]
This is the remainder of the issue reported by #10

**Comment by easel** [comment]
As an aside, it *appears* as if the presence of any path statement (in v0.6.0)  prevents the tunnel from getting provisioned properly.

**Comment by easel** [comment]
Confirmed. To reproduce, just follow the instructions from https://developers.cloudflare.com/argo-tunnel/reference/kubernetes/ but replace this:
```
  - host: echo.mydomain.com
    http:
      paths:
      - backend:
          serviceName: echo
          servicePort: http
```

with 

```
  - host: echo.mydomain.com
    http:
      paths:
      - path: /
         backend:
           serviceName: echo
           servicePort: http
```

The host will never be added in Cloudflare. Scrub out the `path: /` and re-apply and it pops up.

**Comment by mattalberts** [comment]
That’s correct, path based routing isn’t supported. Rather that ignoring the path and establishing a tunnel base on host:port, in the 0.6.x line I decided to explicitly error on t tunnel creation. You’ll see a corresponding error log stating that path based routing is not supported .... that said I should have eased that restriction to empty string and “/“,  .... I’ll update

**Comment by easel** [comment]
@mattalberts that would help, I ran into two helm charts back to back that wouldn't quite work with Cloudflare since it wasn't allowing `path: "/"`. Thanks!

**Comment by nathanwaters** [comment]
If the current version supports multiple rules (not paths), how do you add multiple tls hostnames?

This doesn't work (Cloudflare DNS backend doesn't add the CNAME's):

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: argo-tunnel
  labels:
    ingress: argo-tunnel
  name: ingress-argo
spec:
  tls:
  - hosts:
    - one.example.com
    secretName: example.com
  - hosts:
    - two.example.com
    secretName: example.com    
  rules:
  - host: one.example.com
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: 8080
  - host: two.example.com
    http:
      paths:
      - backend:
          serviceName: service2
          servicePort: 8080
```
