### ISSUE TITLE
Rolling-update without load balancer possible?

### ISSUE THREAD

**Issue by acrogenesis** [cloudflare/cloudflare-ingress-controller#165]
I know we can't have several replicas without using Load Balancers but can we do rolling updates?
```
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
```
So what happens is the new pod starts and is running and the old pod terminates until the readiness probe is finished. Will argo-tunnel update it's reference accordingly? And not have trouble?

Thanks
