### ISSUE TITLE
Support for ExternalName Services

### ISSUE THREAD

**Issue by grrywlsn** [cloudflare/cloudflare-ingress-controller#168]
I've been using the Cloudflare ingress controller with services inside Kubernetes successfully for months (running 0.6.5). I'd also like to be able to use the same ingress controller to route traffic to services accessible to, but outside of, Kubernetes.

In this scenario, I want to be able to expose Vault's UI (accessible on an AWS ELB), to Kubernetes as a Service, which can then be used as a backend service for a Cloudflare ingress. This would make use of the ExternalName service: https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-mapping-external-services

I believe something like this is what I'd need to do, but it seems Cloudflare can't support it yet:

```
apiVersion: v1
kind: Service
metadata:
  name: vault-ui
spec:
  type: ExternalName
  externalName: vault-ui.eu-west-1.elb.amazonaws.com
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: argo-tunnel
  name: vault-ui
spec:
  rules:
  - host: vault-ui.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: vault-ui
          servicePort: https
```

I think the reason it doesn't work yet is that a Service with `ExternalName` doesn't have any Endpoints; however, the DNS and port can be curl'd from within the Cloudflare ingress container. I get error: `err: \"endpoints 'default/vault-ui' do not exist\""`

Is this something that could be added?
