### ISSUE TITLE
User cannot list resource in API group at the cluster scope

### ISSUE THREAD

**Issue by RemiVillien** [cloudflare/cloudflare-ingress-controller#94]
Hi,

After following the doc, I get this when I log the ingress-controller
```
E1029 16:16:28.196566       1 reflector.go:205] github.com/cloudflare/cloudflare-ingress-controller/pkg/controller/controller.go:319: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:default:cloudflare-argo" cannot list resource "services" in API group "" at the cluster scope
E1029 16:16:28.273495       1 reflector.go:205] github.com/cloudflare/cloudflare-ingress-controller/pkg/controller/controller.go:320: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:default:cloudflare-argo" cannot list resource "endpoints" in API group "" at the cluster scope
E1029 16:16:28.666380       1 reflector.go:205] github.com/cloudflare/cloudflare-ingress-controller/pkg/controller/controller.go:321: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:default:cloudflare-argo" cannot list resource "ingresses" in API group "extensions" at the cluster scope
```
I really don't understand what I did wrong.

Here is my deployment
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dwoom-account-frontend
  name: dwoom-account-frontend
  namespace: default
spec:
  progressDeadlineSeconds: 60
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dwoom-account-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dwoom-account-frontend
    spec:
      containers:
      - image: registry.gitlab.com/dwoom/account/frontend:dev-build
        imagePullPolicy: Always
        name: dwoom-account-frontend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

```

My service

```yaml
kind: Service
apiVersion: v1
metadata:
  name: dwoom-account-frontend-argo
spec:
  selector:
    app: dwoom-account-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
```

And my warp-controller

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: argo-tunnel
  name: dwoom-account-frontend-ingress
  namespace: default
spec:
  rules:
  - host: account.dwoom.com
    http:
      paths:
      - backend:
          serviceName: dwoom-account-frontend
          servicePort: 80
```

I'm new to kubernetes and halm, so all of this is overwhelming. Any idea where I made an error?

**Comment by mattalberts** [comment]
@RemiVillien looks like you are running k8s with RBAC, so you'll need to tell helm to produce the rbac definitions as well.

**Comment by RemiVillien** [comment]
Thanks @mattalberts , I figured that out reading the doc on github. But I have a new issue now :/
The tunel just doesn't appear on the cloudflare DNS tab.
I made a small video to show what I have done in case I made any error : https://www.youtube.com/watch?v=v8P_2o31OHo

I changed few things in my deployment, service & ingress

```yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    app: dwoom-account-frontend
  name: dwoom-account-frontend-argo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dwoom-account-frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dwoom-account-frontend
  name: dwoom-account-frontend
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dwoom-account-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dwoom-account-frontend
    spec:
      containers:
      - image: registry.gitlab.com/dwoom/account/frontend:dev-build
        imagePullPolicy: Always
        name: dwoom-account-frontend
        ports:
        - containerPort: 80
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: argo-tunnel
  labels:
    ingress: argo-tunnel
  name: dwoom-account-frontend-ingress
spec:
  rules:
  - host: account.dwoom.com
    http:
      paths:
      - backend:
          serviceName: dwoom-account-frontend
          servicePort: http
```

And here is the pod logs https://gist.github.com/RemiVillien/1c90c3e6f5e61f815ff297d5cac3a087

I have also contacted the support.
